project_id = "otxlvlxvodzqgwkbyknb"

[functions.calculate-distance]
verify_jwt = false

[functions.calculate-eta]
verify_jwt = false

[functions.get-directions]
verify_jwt = false

[functions.get-route-history]
verify_jwt = false

[functions.cleanup-abandoned-orders]
verify_jwt = false

[functions.seed-test-users]
verify_jwt = false

[functions.sync-order-to-hubspot]
verify_jwt = false
